name: 'App: Create Pre-release Tag'

on:
  workflow_dispatch:
    inputs:
      deploymentEnv:
        type: choice
        required: true
        default: 'stag'
        description: env to deploy on
        options:
          - dev
          - stag
          - beta

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running create-pre-release-tag to deploy on ${{ github.event.inputs.deploymentEnv }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{secrets.PRE_RELEASE_TAG_ACTION}}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json' # setup node using volta config

      - name: Generate Git Tag
        run: npm run release:pre ${{ github.event.inputs.deploymentEnv }} 